env:
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  no-unused-vars:
    - off
  semi:
    - error
    - always
  no-console:
    - off